services:
  backend:
    build: ./backend
    container_name: placementhub_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: placementhub_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
